### PR TITLE
Use silent

### PR DESCRIPTION
**Pull request by Shougo**
I think `silent` should be added.

### CODE REVIEW

**Comment by lambdalisue** [comment]
Why? What was the actual issue here?

**Comment by Shougo** [comment]
Because I get hit-enter prompt by `guise.vim`...

スクリーンショット_2021-11-17_14-28-18

**Comment by lambdalisue** [comment]
Hum... Then why you don't get that message when you hit `:e {filename}` manually or whatever?

**Comment by Shougo** [comment]
I don't know why.  But I get prompts by `tabedit`...

**Comment by lambdalisue** [comment]
OK. Using `silent` may cause some side-effects but I'll think about it then.

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
